# Generated by Django 5.0.3 on 2024-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0005_order_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('accessory_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessory_name', models.CharField(max_length=50)),
                ('accessory_type', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='accessory_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='food_pics')),
            ],
        ),
    ]
