# Generated by Django 5.0.3 on 2024-05-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0006_accessory_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
