# Generated by Django 5.0.3 on 2024-05-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0007_delete_accessory_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Collars', 'Collars'), ('Leashes', 'Leashes'), ('Toys', 'Toys'), ('Beds', 'Beds'), ('Bowls', 'Bowls'), ('Clothing', 'Clothing'), ('Grooming', 'Grooming')], default='Collars', max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='accessory_pics')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petStoreApp.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Dry Food', 'Dry Food'), ('Wet Food', 'Wet Food'), ('Treats', 'Treats')], default='Dry Food', max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='food_pics')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petStoreApp.pet')),
            ],
        ),
    ]
