# Generated by Django 5.0.3 on 2024-05-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0010_remove_accessory_id_remove_food_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='image',
        ),
    ]
