# Generated by Django 5.0.3 on 2024-05-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0011_remove_accessory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='pet',
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
