# Generated by Django 5.0.3 on 2024-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0013_petproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Toy', 'Toy'), ('Accessory', 'Accessory'), ('Food', 'Food'), ('Grooming', 'Grooming')], max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_pics')),
            ],
        ),
        migrations.DeleteModel(
            name='PetProducts',
        ),
    ]
