# Generated by Django 5.0.3 on 2024-05-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0017_alter_order_is_completed_alter_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
