# Generated by Django 5.0.3 on 2024-05-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0020_pet_pet_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_label',
        ),
    ]
