# Generated by Django 5.0.3 on 2024-05-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0021_remove_pet_pet_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetProduct',
        ),
    ]
