# Generated by Django 5.0.3 on 2024-05-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0025_rename_pet_name_pet_product_name_alter_pet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='proof'),
        ),
    ]
