# Generated by Django 5.0.3 on 2024-05-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0032_dashboarddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
