# Generated by Django 5.0.3 on 2024-05-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petStoreApp', '0033_groomingreservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardData',
        ),
        migrations.DeleteModel(
            name='GroomingReservation',
        ),
    ]
